console.log(Math)
console.log(Math.PI)
console.log(Math.abs(-8.5))
console.log(Math.ceil(2.1))
console.log(Math.floor(8.9))
console.log(Math.round(5.4))
console.log(Math.pow(5,2))
console.log(Math.random())
console.log(Math.round(Math.random() * 100) )